#############################################################################
# Makefile for building: serwerStrzalka
# Generated by qmake (2.01a) (Qt 4.6.3) on: niedz. cze 2 19:39:03 2013
# Project:  serwerStrzalka.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile serwerStrzalka.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtSql -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Database/DataAccessObject.cpp \
		Exceptions/Exception.cpp \
		Exceptions/BadPackageException.cpp \
		Logic/Server.cpp \
		Logic/PacketController.cpp \
		Logic/ConnectionPool.cpp \
		Parser/ProtocolParser.cpp \
		Socket/TcpSocket.cpp \
		Logic/ClientHandler.cpp moc_ClientHandler.cpp
OBJECTS       = main.o \
		DataAccessObject.o \
		Exception.o \
		BadPackageException.o \
		Server.o \
		PacketController.o \
		ConnectionPool.o \
		ProtocolParser.o \
		TcpSocket.o \
		ClientHandler.o \
		moc_ClientHandler.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		serwerStrzalka.pro
QMAKE_TARGET  = serwerStrzalka
DESTDIR       = 
TARGET        = serwerStrzalka

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: serwerStrzalka.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile serwerStrzalka.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile serwerStrzalka.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/serwerStrzalka1.0.0 || $(MKDIR) .tmp/serwerStrzalka1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/serwerStrzalka1.0.0/ && $(COPY_FILE) --parents Database/DataAccessObject.h Exceptions/Exception.h Exceptions/BadPackageException.h Logic/Server.h Logic/Packets.h Logic/PacketController.h Logic/ConnectionPool.h Parser/ProtocolParser.h Parser/PacketType.h Socket/TcpSocket.h Logic/ClientHandler.h .tmp/serwerStrzalka1.0.0/ && $(COPY_FILE) --parents main.cpp Database/DataAccessObject.cpp Exceptions/Exception.cpp Exceptions/BadPackageException.cpp Logic/Server.cpp Logic/PacketController.cpp Logic/ConnectionPool.cpp Parser/ProtocolParser.cpp Socket/TcpSocket.cpp Logic/ClientHandler.cpp .tmp/serwerStrzalka1.0.0/ && (cd `dirname .tmp/serwerStrzalka1.0.0` && $(TAR) serwerStrzalka1.0.0.tar serwerStrzalka1.0.0 && $(COMPRESS) serwerStrzalka1.0.0.tar) && $(MOVE) `dirname .tmp/serwerStrzalka1.0.0`/serwerStrzalka1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/serwerStrzalka1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ClientHandler.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ClientHandler.cpp
moc_ClientHandler.cpp: Socket/TcpSocket.h \
		Logic/PacketController.h \
		Logic/Packets.h \
		Database/DataAccessObject.h \
		Parser/ProtocolParser.h \
		Parser/PacketType.h \
		Logic/ClientHandler.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Logic/ClientHandler.h -o moc_ClientHandler.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp Logic/Server.h \
		Logic/ConnectionPool.h \
		Logic/ClientHandler.h \
		Socket/TcpSocket.h \
		Logic/PacketController.h \
		Logic/Packets.h \
		Database/DataAccessObject.h \
		Parser/ProtocolParser.h \
		Parser/PacketType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

DataAccessObject.o: Database/DataAccessObject.cpp Database/DataAccessObject.h \
		Logic/Packets.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DataAccessObject.o Database/DataAccessObject.cpp

Exception.o: Exceptions/Exception.cpp Exceptions/Exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Exception.o Exceptions/Exception.cpp

BadPackageException.o: Exceptions/BadPackageException.cpp Exceptions/BadPackageException.h \
		Exceptions/Exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BadPackageException.o Exceptions/BadPackageException.cpp

Server.o: Logic/Server.cpp Logic/Server.h \
		Logic/ConnectionPool.h \
		Logic/ClientHandler.h \
		Socket/TcpSocket.h \
		Logic/PacketController.h \
		Logic/Packets.h \
		Database/DataAccessObject.h \
		Parser/ProtocolParser.h \
		Parser/PacketType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Server.o Logic/Server.cpp

PacketController.o: Logic/PacketController.cpp Logic/PacketController.h \
		Logic/Packets.h \
		Socket/TcpSocket.h \
		Database/DataAccessObject.h \
		Parser/ProtocolParser.h \
		Parser/PacketType.h \
		Exceptions/BadPackageException.h \
		Exceptions/Exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PacketController.o Logic/PacketController.cpp

ConnectionPool.o: Logic/ConnectionPool.cpp Logic/ConnectionPool.h \
		Logic/ClientHandler.h \
		Socket/TcpSocket.h \
		Logic/PacketController.h \
		Logic/Packets.h \
		Database/DataAccessObject.h \
		Parser/ProtocolParser.h \
		Parser/PacketType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConnectionPool.o Logic/ConnectionPool.cpp

ProtocolParser.o: Parser/ProtocolParser.cpp Parser/ProtocolParser.h \
		Parser/PacketType.h \
		Logic/Packets.h \
		Exceptions/BadPackageException.h \
		Exceptions/Exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProtocolParser.o Parser/ProtocolParser.cpp

TcpSocket.o: Socket/TcpSocket.cpp Socket/TcpSocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TcpSocket.o Socket/TcpSocket.cpp

ClientHandler.o: Logic/ClientHandler.cpp Logic/ClientHandler.h \
		Socket/TcpSocket.h \
		Logic/PacketController.h \
		Logic/Packets.h \
		Database/DataAccessObject.h \
		Parser/ProtocolParser.h \
		Parser/PacketType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ClientHandler.o Logic/ClientHandler.cpp

moc_ClientHandler.o: moc_ClientHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ClientHandler.o moc_ClientHandler.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

